name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Linter
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
    - name: Check code style
      # TODO: find out why Ubuntu refuses to 
      # run: rustfmt --check ./src/**/*.rs
      # run: rustfmt --check ./src/*.rs
      run: |
        shopt -s globstar
        rustfmt --check ./src/**/*.rs

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  
  # TODO: have publish only run when precheck + test pass
  # TODO: build and publish release builds when triggered from a tag
  # TODO: publish crates to crates.io and packages to github
  # TODO: publish user docs to GH pages
  # TODO: publish API docs to docs.rs
  publish-dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: sample_linux
        path: target/debug/sample
        