name: Rust

# TODO: run build on every push regardless of branch
#       may run into problems publishing artifacts
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Linter
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
    - name: Check code style
      # NOTE: we have to set the BASH shell option 'globstar'
      #       for the **/*.rs syntax to work. Apparently this
      #       feature is disabled by default for some reason
      run: |
        shopt -s globstar
        rustfmt --check ./src/**/*.rs

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  
  # TODO: build and publish 3 separate binaries, for each major OS platform
  # TODO: build and publish release builds when triggered from a tag
  # TODO: publish crates to crates.io and packages to github
  # TODO: publish user docs to GH pages
  # TODO: publish API docs to docs.rs
  publish-dev:
    # Only publish when previous build steps finish successfully
    needs: [precheck, test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Linux
      # similar to: cargo build --target=x86_64-unknown-linux-gnu --verbose
      run: cargo build --verbose
    - name: Publish Linux
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: target/debug/sample

    - name: Build MacOS
      run: |
        apt install -y clang gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev
        rustup target add x86_64-apple-darwin
        cargo build --target=x86_64-apple-darwin --verbose
    - name: Publish MacOS
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: target/debug/sample
        